trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureWebAppContainer@1
    inputs:
      azureSubscription: 'Azure subscription 1(1)(ad0b6680-22b4-4c62-bc36-6d9daf8e9ff6)'
      appName: 'BeeShelfApi'
      deployToSlotOrASE: true
      resourceGroupName: 'BeeStore'
      slotName: 'production'
      containers: 'beestorecontainer.azurecr.io/beestorecicd:latest'
