trigger:
- dev

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '81f64ba0-95fc-4d01-8f0f-68732968cd25'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'
stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
      - task: Docker@2
        displayName: 'Build Docker Image'
        inputs:
          containerRegistry: '$(dockerRegistryServiceConnection)'
          repository: 'beestorecicd'
          command: 'build'
          Dockerfile: '**/Dockerfile'
          buildContext: '$(System.DefaultWorkingDirectory)'
          tags: |
            $(Build.BuildId)
            latest
          arguments: |
            --build-arg AZURE_CLIENT_ID=$(AZURE_CLIENT_ID)
            --build-arg AZURE_TENANT_ID=$(AZURE_TENANT_ID)
            --build-arg AZURE_CLIENT_SECRET=$(AZURE_CLIENT_SECRET)

      - task: Docker@2
        displayName: 'Push Docker Image'
        inputs:
          containerRegistry: '$(dockerRegistryServiceConnection)'
          repository: 'beestorecicd'
          command: 'push'
          tags: |
            $(Build.BuildId)
            latest
        
